# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  #  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  encoding: utf8
  database: parking
  username: postgres
  password: 123456
  host: localhost

production:
  <<: *default
  url: 'postgres://osuculppyyxnhz:706cd40fc587674e312b3727f55b90b0fc11df570a2215bef7482a7952a0b04a@ec2-75-101-133-29.compute-1.amazonaws.com:5432/d5qqvafnikt811'


